-- Check schema for Form related tables
USE EmployeePerformance;
GO

PRINT '--- ApplicationForms ---';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ApplicationForms'
ORDER BY ORDINAL_POSITION;

PRINT '--- AppraisalQuestions ---';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'AppraisalQuestions'
ORDER BY ORDINAL_POSITION;

PRINT '--- FormQuestions ---';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FormQuestions'
ORDER BY ORDINAL_POSITION;

PRINT '--- PerformanceEvaluations ---';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PerformanceEvaluations'
ORDER BY ORDINAL_POSITION;

PRINT '--- AppraisalResponses ---';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'AppraisalResponses'
ORDER BY ORDINAL_POSITION;
GO